# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='班级名称')),
                ('number', models.IntegerField(verbose_name='班级人数')),
            ],
            options={
                'verbose_name': '实验班级',
                'verbose_name_plural': '实验班级',
            },
        ),
    ]
