# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 19:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('measure', '0002_auto_20181115_1934'),
        ('courses', '0002_auto_20181115_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPublic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='实验开始时间')),
                ('stop_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='实验结束时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='measure.Laboratory', verbose_name='所在实验室')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='发布实验')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='实验教师')),
            ],
            options={
                'verbose_name': '实验发布',
                'verbose_name_plural': '实验发布',
            },
        ),
        migrations.CreateModel(
            name='LessonSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0, verbose_name='实验分数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='预约实验')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='实验学生')),
            ],
            options={
                'verbose_name': '实验预约',
                'verbose_name_plural': '实验预约',
            },
        ),
    ]
