# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 09:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opertion', '0002_auto_20181204_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='报告标题')),
                ('download', models.FileField(upload_to='lesson/report/%Y/%m', verbose_name='报告文本')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opertion.LessonSubscribe', verbose_name='所属实验')),
            ],
            options={
                'verbose_name': '实验报告',
                'verbose_name_plural': '实验报告',
            },
        ),
    ]
