# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opertion', '0003_lessonreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsubscribe',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
    ]
