# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0007_auto_20181213_1432'),
        ('opertion', '0005_lessonpublic_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsubscribe',
            name='desk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='measure.Desk', verbose_name='预约实验台'),
        ),
    ]
