# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 20:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='课程名')),
                ('desc', models.CharField(max_length=300, verbose_name='课程描述')),
                ('detail', models.TextField(verbose_name='课程说明')),
                ('student', models.IntegerField(default=0, verbose_name='学习人数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='课程点击量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='资料名称')),
                ('download', models.FileField(upload_to='course', verbose_name='科目资料')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='资料所对应的科目')),
            ],
            options={
                'verbose_name': '科目资源',
                'verbose_name_plural': '科目资源',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='实验名称')),
                ('detail', models.TextField(verbose_name='实验要求')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='实验所对应的科目')),
            ],
            options={
                'verbose_name': '实验课',
                'verbose_name_plural': '实验课',
            },
        ),
        migrations.CreateModel(
            name='LessonFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='实验资料名称')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='实验资料')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='实验课')),
            ],
            options={
                'verbose_name': '实验资料',
                'verbose_name_plural': '实验资料',
            },
        ),
    ]
