# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='labs',
            field=models.ManyToManyField(to='measure.Laboratory', verbose_name='实验室'),
        ),
    ]
