# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 20:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='课程名')),
                ('detail', models.TextField(verbose_name='课程说明')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='实验名称')),
                ('detail', models.TextField(verbose_name='实验要求')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('teacher', models.CharField(default='ykk', max_length=20, verbose_name='实验教师')),
                ('lesson_start', models.DateTimeField(verbose_name='实验起始时间')),
                ('lesson_stop', models.DateTimeField(verbose_name='实验结束时间')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='所属科目')),
                ('labs', models.ManyToManyField(to='measure.Laboratory', verbose_name='实验室')),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='选此实验的学生')),
            ],
            options={
                'verbose_name': '实验课',
                'verbose_name_plural': '实验课',
            },
        ),
    ]
