# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 19:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='资料名称')),
                ('download', models.FileField(upload_to='lesson/resource/%Y/%m', verbose_name='实验资料')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='labs',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_start',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_stop',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='students',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.AddField(
            model_name='lesson',
            name='template',
            field=models.FileField(blank=True, null=True, upload_to='lesson/template/%Y/%m', verbose_name='实验模板'),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='所属实验'),
        ),
    ]
