# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20181115_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='detail',
            field=models.TextField(default='', verbose_name='实验说明'),
        ),
    ]
