# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 20:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='仪器名称')),
                ('kind', models.CharField(max_length=10, verbose_name='仪器属性')),
                ('brand', models.CharField(default='Tektronix', max_length=10, verbose_name='品牌')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='购买时间')),
                ('detail', models.TextField(default='123', verbose_name='仪器说明')),
            ],
            options={
                'verbose_name': '仪器名称',
                'verbose_name_plural': '仪器名称',
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='实验室名称')),
                ('locate', models.CharField(default='基础实验楼', max_length=30, verbose_name='实验室位置')),
                ('admin', models.CharField(default='ykk', max_length=10, verbose_name='实验室管理员')),
                ('detail', models.TextField(default='123', verbose_name='实验室介绍')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('open_start', models.DateTimeField(verbose_name='实验室开放时间')),
                ('open_stop', models.DateTimeField(verbose_name='实验室开放结束时间')),
            ],
            options={
                'verbose_name': '实验室名称',
                'verbose_name_plural': '实验室名称',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measure.Laboratory', verbose_name='信号源所属的实验室'),
        ),
    ]
