# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 19:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='capacity',
            field=models.IntegerField(default=80, verbose_name='实验室容量'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='open_start',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='实验室开放时间'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='open_stop',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='实验室开放结束时间'),
        ),
    ]
