# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0003_auto_20181212_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desk',
            options={'verbose_name': '试验台编号', 'verbose_name_plural': '试验台编号'},
        ),
    ]
