# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0004_auto_20181212_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desk',
            options={'verbose_name': '实验台编号', 'verbose_name_plural': '实验台编号'},
        ),
    ]
