# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='实验标题')),
                ('content', models.TextField(verbose_name='实验内容')),
            ],
            options={
                'verbose_name': '实验模板',
                'verbose_name_plural': '实验模板',
            },
        ),
    ]
